### PR TITLE
Integrated Danger

### PR DESCRIPTION
**Pull request by vitalii-tym**
This PR adds Danger to the Gemfile. The tool will be triggered from .travis.yml after all other operations have finished. Ticket: https://github.com/CodeDoesGood/business/issues/109

To test that it works, try creating a PR with a comment less than 5 characters - it will complain about the comment being empty.

No special rules as well as no additional Danger plugins were added yet. Those are better to be created in separate tickets to avoid "all-in-one" tasks.

For the Danger to be able to set PR status this bot account has to be invited to the team and its respective token should be added into Travis CI: https://github.com/Bot4CodeDoesGood

### CODE REVIEW

**Comment by vitalii-tym** [comment]
The build fails because there is no key for cocoapods-keys configured in Travis CI.
~~Whoever has admin rights to the github account, please go to the Travis settings and add this environment variable:
NETWORKAPITOKEN=test~~

OK, I don't know why but I was able to do this.

**Comment by vitalii-tym** [comment]
Travis and Danger seem to be working together now. The cocapods-keys seems to be working too, at least it is still in there and the build runs fine.

@GrfxGuru Peter, could you please invite the bot account (https://github.com/Bot4CodeDoesGood) into the CodeDoesGood org to let the bot change the PR status. (This is optional, the bot can already make comments, adding it to the org only needed to influence on the status.)
It would be also good to change ownership of the bot account to an e-mail owned by the org. Let me know which e-mail I should use for this.

(note that GitHub only allows one bot account per org, so if there is already a bot account present - please let me know so that we change the DANGER_GITHUB_API_TOKEN to an already existing bot).

**Comment by vitalii-tym** [comment]
There is one glitch though: sometimes the build fails due to the Xcode tests failing to run. They are timeouting with different errors. For example:

```
2017-06-12 08:49:56.512 XCTRunner[7367:18456] Running tests...
Failed to run tests: Timeout out trying to establish connection to IDE.test
2017-06-12 08:51:09.057 xcodebuild[6777:14631] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
2017-06-12 08:51:09.057 xcodebuild[6777:14631] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
```
There is no straightforward solution. A lot of potential fixes found at Stackoverflow, so we'll need to play with this issue a little longer finding the best solution that will work for us. This is not related to Danger, so I'll create a separate ticket for this issue.

**Comment by festrs** [comment]
see this https://github.com/travis-ci/travis-ci/issues/6422 @vitalii-tym

**Comment by vitalii-tym** [comment]
@festrs, thanks! 
I've used all most successful workarounds. It seems to be working now.

**Comment by tehstun** [comment]
@swiftcode is this meant to be sat here?

**Comment by northtwilight** [comment]
If I'm in error merging this PR just revert. Seems this might be useful in future though

**Pull request merged**
